server:
  port: 8080
spring:
  application:
    name: user-management-system
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  hibernate:
    show_sql: true

logging:
  level:
    root: info