server:
  port: 8080
    #servlet:
  #context-path=api: api
spring:
  application:
    name: user-management-system
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

logging:
  level:
    root: debug
